# Generated by Django 5.2.8 on 2025-11-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_poslugs',
            name='posluga',
            field=models.CharField(default='zakrutu semestr', max_length=120),
        ),
        migrations.AlterField(
            model_name='client_poslugs',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
