# Generated by Django 5.2.8 on 2025-11-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_db', '0002_client_poslugs_posluga_alter_client_poslugs_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_poslugs',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_poslugs',
            name='posluga',
            field=models.CharField(default='закрити семестр', max_length=120),
        ),
    ]
