# Generated by Django 5.2.8 on 2025-11-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_db', '0003_alter_client_poslugs_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_poslugs',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client_poslugs',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
